services:
  client:
    container_name: vite-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      # - "node_modules:/app/node_modules"
      - "/app/node_modules"
    environment:
      - "CHOKIDAR_USEPOLLING=true"
      - WATCHPACK_POLLING=true
# volumes:
#   node_modules:
