services:
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - "CHOKIDAR_USEPOLLING=true"
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    depends_on:
      - db 

volumes:
  postgres_data: