services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forex
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    container_name: client
    build:
      context: ./aisoft
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./aisoft:/app"
      - "/app/node_modules"
    environment:
      - "CHOKIDAR_USEPOLLING=true"
      - WATCHPACK_POLLING=true
    env_file:
      - ./aisoft/.env
    depends_on:
      - db

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --forward-to http://client:3000/api/webhook --api-key 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"
    env_file:
      - ./aisoft/.env

  python-services:
    build:
      context: ./temp_ai
      dockerfile: Dockerfile
    container_name: python-services
    depends_on:
      - db  # Remove this if the scripts don't need PostgreSQL
    volumes:
      - "./temp_ai:/app"
    ports:
      - "5555:5555"
    command: >
      sh -c "
      python /app/server.py & 
      python /app/checkduebill.py & 
      python /app/updatemodel_EURUSD.py & 
      python /app/updatemodel_GBPUSD.py & 
      python /app/updatemodel_USDJPY.py & 
      wait"
volumes:
  postgres_data:
